[View in Colaboratory](https://colab.research.google.com/github/udemeudofia/stanford-tensorflow-tutorials/blob/master/CS20_Assignment_1.ipynb)

In [32]:
import tensorflow as tf
import numpy as np

sess = tf.InteractiveSession()
x=3
y=4
a=tf.multiply(x,x)
b=tf.multiply(a,y)
c=tf.add(y,2)
i=tf.add(b,c)

print(sess.run(i))


42


In [2]:
#Use tf.cond() in writing conditional statements

p = tf.random_uniform([])
q = tf.random_uniform([])
out = tf.cond(tf.greater(p,q), lambda:p+q, lambda:p-q)
print(out.eval())

1.3321147


In [4]:
#tf.case() is used for conditional statements with more than two conditions

f = tf.random_uniform([], -1,1, dtype=tf.float32)
g = tf.random_uniform([], -1,1, dtype=tf.float32)
out = tf.case({tf.less(f,g): lambda: tf.add(f,g), tf.greater(f,g): lambda: tf.subtract(f,g)}, default=lambda: tf.constant(0.0))
print(sess.run(out))

0.13265204


In [5]:
#Equality check with booleans using tf.equal()

a = tf.constant([[0, -2, -1], [0, 1, 2]])
b = tf.zeros_like(a)
op = tf.equal(a,b)
print(sess.run(op))

[[ True False False]
 [ True False False]]


In [6]:
#Filter and gather cetain values from a range using #tf.where() and tf.gather()

k = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951, 
                 30.97266006,  26.67541885,  38.08450317,  20.74983215,
                 34.94445419,  34.45999146,  29.06485367,  36.01657104,
                 27.88236427,  20.56035233,  30.20379066,  29.51215172,
                 33.71149445,  28.59134293,  36.05556488,  28.66994858])

l = tf.where(k>30)
opt = tf.gather(k,l)
print(sess.run(opt))

[[31.190735]
 [30.97266 ]
 [38.084503]
 [34.944454]
 [34.45999 ]
 [36.01657 ]
 [30.20379 ]
 [33.711494]
 [36.055565]]


In [33]:
#Set diagonals of a matrix

start = 1
limit = 37
delta = 1
q = tf.range(start, limit, delta)
q = tf.reshape(q, [6,6])

diagonal = np.array([1,2,3,4,5,6])
#r = tf.diag(diagonal)

t = tf.matrix_set_diag(q,diagonal)

#print(sess.run(r))
print(sess.run(t))

[[ 1  2  3  4  5  6]
 [ 7  2  9 10 11 12]
 [13 14  3 16 17 18]
 [19 20 21  4 23 24]
 [25 26 27 28  5 30]
 [31 32 33 34 35  6]]


In [8]:
values = tf.range(1, 7)
out = tf.diag(values)
print(sess.run(out))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [34]:
#Create a random 2-d 10x10 matrix and determine the determinant

x = tf.random_uniform([10,10], minval=0, maxval=20, dtype=tf.float32)
y = tf.matrix_determinant(x)
print(sess.run(y))

53114150000.0


In [13]:
#Find the unique element from a tensor

x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
y = tf.unique(x)
print(sess.run(y))

Unique(y=array([ 5,  2,  3, 10,  6,  4,  1,  0,  9], dtype=int32), idx=array([0, 1, 2, 0, 3, 4, 1, 2, 5, 1, 6, 6, 7, 8], dtype=int32))


In [47]:
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.cond() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.


x = tf.random_normal([300], 0, 50)
y = tf.random_normal([300], 0, 50)
#z = tf.add(x,y)

#tf.square(x-y)
#tf.reduce_sum(tf.abs(x-y))
#tf.less(tf.reduce_mean(x-y),0)
p = tf.cond(tf.less(tf.reduce_mean(x-y),0), lambda:tf.square(x-y), lambda:tf.reduce_sum(tf.abs(x-y)))
print(sess.run(p))

17259.96
